// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.1
// source: proto/attest/attest.proto

package attest

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AttestService_Attest_FullMethodName = "/attest.AttestService/Attest"
)

// AttestServiceClient is the client API for AttestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AttestServiceClient interface {
	Attest(ctx context.Context, in *AttestRequest, opts ...grpc.CallOption) (*AttestReply, error)
}

type attestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAttestServiceClient(cc grpc.ClientConnInterface) AttestServiceClient {
	return &attestServiceClient{cc}
}

func (c *attestServiceClient) Attest(ctx context.Context, in *AttestRequest, opts ...grpc.CallOption) (*AttestReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttestReply)
	err := c.cc.Invoke(ctx, AttestService_Attest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AttestServiceServer is the server API for AttestService service.
// All implementations must embed UnimplementedAttestServiceServer
// for forward compatibility.
type AttestServiceServer interface {
	Attest(context.Context, *AttestRequest) (*AttestReply, error)
	mustEmbedUnimplementedAttestServiceServer()
}

// UnimplementedAttestServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAttestServiceServer struct{}

func (UnimplementedAttestServiceServer) Attest(context.Context, *AttestRequest) (*AttestReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Attest not implemented")
}
func (UnimplementedAttestServiceServer) mustEmbedUnimplementedAttestServiceServer() {}
func (UnimplementedAttestServiceServer) testEmbeddedByValue()                       {}

// UnsafeAttestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AttestServiceServer will
// result in compilation errors.
type UnsafeAttestServiceServer interface {
	mustEmbedUnimplementedAttestServiceServer()
}

func RegisterAttestServiceServer(s grpc.ServiceRegistrar, srv AttestServiceServer) {
	// If the following call pancis, it indicates UnimplementedAttestServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AttestService_ServiceDesc, srv)
}

func _AttestService_Attest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttestServiceServer).Attest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttestService_Attest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttestServiceServer).Attest(ctx, req.(*AttestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AttestService_ServiceDesc is the grpc.ServiceDesc for AttestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AttestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "attest.AttestService",
	HandlerType: (*AttestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Attest",
			Handler:    _AttestService_Attest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/attest/attest.proto",
}
